buildpack: https://github.com/enricobacis/packager-buildpack-qt

targets:
  ubuntu-14.04:
    build_dependencies:
      - qt-sdk
      - qtmultimedia5-dev
    dependencies:
      - libqt5multimedia5-plugins

default_dependencies: false

cli: Qubet
