Qubet: Cube Class Reference
Cube Class Reference
This class rapresents the player's Cube.
#include <cube.h>
Signals
void levelCompleted ()
Signal emitted when the level is completed.
void suicide ()
Signal emitted when the player "suicide" the Cube.
void explosionFinished ()
Signal to inform that the explosion has finished.
void hideLevelName ()
Signal to inform to hide the level name.
void playEffect (QString effectName)
Signal emitted to play an effect.
Public Member Functions
Cube (Level *_level, Skin *_skin, QObject *_parent=0, QGLShaderProgram *_explosionShader=NULL)
Create a Cube.
~Cube ()
Safely destroy a Cube object.
void startCube ()
Start the motion of the Cube;.
void stopCube ()
Stop the motion of the Cube.
Vector3f * getPosition ()
Returns the position of the Cube.
GLfloat getZ ()
Returns the Z of the Cube.
void setPosition (Vector3f *_position)
Set the position of the Cube.
void jump ()
Make the Cube jump.
bool isMoving ()
Returns true if the Cube is moving, else false.
void moveLeft ()
Make the Cube move to the Left.
void moveRight ()
Make the Cube move to the right.
void draw (GLboolean simplifyForPicking=false)
Draw the Cube.
void updatePosition ()
Update the position of the Cube.
Private Slots
void collided ()
It is the slot invoked when the Cube collides with an Obstacle.
void keyPressed (QKeyEvent *event)
Slot invoked when the user presses a key on the keyboard.
Private Member Functions
void createNormalsMatrix ()
Generate the normalsMatrix Matrix.
void drawExplosion ()
this function is called in the draw function in case of explosion.
void explode ()
Make the Cube explode.
void completed ()
Actions to perform when the level is completed.
void resetCube ()
Reset the Level.
Private Attributes
Skin * skin
QObject * parent
Vector3f * position
unsigned char state
GLfloat speed
GLfloat gravity
GLint levelCellsLength
GLint levelCellsWidth
GLfloat scaleFactor
GLfloat jumpStartTime
GLint jumpStep
GLint movingStep
GLint explosionStep
GLint xCell
Vector3f * normalsMatrix [4][4][4]
Vector3f * anglesMatrix [4][4][4]
GLint startXCell
bool canMove
QGLShaderProgram * explosionShader
Detailed Description
This class rapresents the player's Cube.
Version:
1.0
Author:
#34
Constructor & Destructor Documentation
Cube::Cube (Level * _level, Skin * _skin, QObject * _parent = 0, QGLShaderProgram * _explosionShader = NULL) [explicit]
Create a Cube.
Parameters:
_level is the Level in which the Cube lives.
_skin is the skin of the Cube.
_parent is the parent of the Cube.
_explosionShader is the shader for the explosion.
References canMove, collided(), createNormalsMatrix(), explosionFinished(), Level::getGravity(), Level::getLength(), Level::getWidth(), gravity, hideLevelName(), keyPressed(), levelCellsLength, levelCellsWidth, levelCompleted(), parent, playEffect(), resetCube(), startXCell, and suicide().
Member Function Documentation
void Cube::draw (GLboolean simplifyForPicking = false)
Draw the Cube.
Parameters:
simplifyForPicking [default = false] is used to draw a simplified scene used for the picking function.
References canMove, drawExplosion(), explosionFinished(), explosionShader, explosionStep, position, resetCube(), skin, state, updatePosition(), Vector3f::x, and Vector3f::y.
Referenced by Game::draw().
Vector3f * Cube::getPosition ()
Returns the position of the Cube.
Returns:
the position of the Cube.
References position.
Referenced by PositionController::checkCollision().
GLfloat Cube::getZ ()
Returns the Z of the Cube.
Returns:
the Z of the Cube.
References position, and Vector3f::z.
Referenced by Game::draw().
bool Cube::isMoving ()
Returns true if the Cube is moving, else false.
Returns:
true if the Cube is moving, else false.
References state.
Referenced by moveLeft(), and moveRight().
void Cube::keyPressed (QKeyEvent * event) [private, slot]
Slot invoked when the user presses a key on the keyboard.
Parameters:
event is the QKeyEvent*.
References canMove, collided(), jump(), moveLeft(), moveRight(), and suicide().
Referenced by Cube().
void Cube::playEffect (QString effectName) [signal]
Signal emitted to play an effect.
Parameters:
effectName is the name of the effect to play.
Referenced by collided(), Cube(), jump(), moveLeft(), and moveRight().
void Cube::setPosition (Vector3f * _position)
Set the position of the Cube.
Parameters:
_position is the position to set.
References position.
Member Data Documentation
Vector3f* Cube::anglesMatrix[4][4][4] [private]
It is the 3-dimensional matrix that contain the nomrs vector of each sub-cube in case of explosion.
Referenced by createNormalsMatrix(), and drawExplosion().
bool Cube::canMove [private]
States if the cube can move or not.
Referenced by completed(), Cube(), draw(), jump(), keyPressed(), moveLeft(), moveRight(), startCube(), stopCube(), and updatePosition().
QGLShaderProgram* Cube::explosionShader [private]
It is the explosion Shader.
Referenced by draw().
GLint Cube::explosionStep [private]
It is the current explosion step.
Referenced by draw(), drawExplosion(), and resetCube().
GLfloat Cube::gravity [private]
It is the gravity variable.
Referenced by Cube(), and updatePosition().
GLfloat Cube::jumpStartTime [private]
It is the time the Cube has started the jump.
GLint Cube::jumpStep [private]
It is the parameter of the jump.
Referenced by resetCube(), and updatePosition().
GLint Cube::levelCellsLength [private]
It is the number of cells of the Level's length.
Referenced by Cube(), and updatePosition().
GLint Cube::levelCellsWidth [private]
It is the number of cells of the Level's width.
Referenced by Cube(), and moveRight().
GLint Cube::movingStep [private]
It is the current moving step for to left and right.
Referenced by resetCube(), and updatePosition().
Vector3f* Cube::normalsMatrix[4][4][4] [private]
It is the 3-dimensional matrix that contain the nomrs vector of each sub-cube in case of explosion.
Referenced by createNormalsMatrix(), and drawExplosion().
QObject* Cube::parent [private]
It is the Parent of the Cube.
Referenced by Cube(), and ~Cube().
Vector3f* Cube::position [private]
It is the Cube's current position.
Referenced by draw(), getPosition(), getZ(), resetCube(), setPosition(), and updatePosition().
GLfloat Cube::scaleFactor [private]
It is the scale factor.
Skin* Cube::skin [private]
It is the Skin of the Cube.
Referenced by draw().
GLfloat Cube::speed [private]
It is the current speed of the Cube.
GLint Cube::startXCell [private]
It is the starting x cell.
Referenced by Cube(), and resetCube().
unsigned char Cube::state [private]
It is the state of the cube.
Referenced by draw(), explode(), isMoving(), jump(), moveLeft(), moveRight(), resetCube(), and updatePosition().
GLint Cube::xCell [private]
It is the x cell the Cube is on.
Referenced by moveLeft(), moveRight(), and resetCube().
The documentation for this class was generated from the following files:
cube.h
cube.cpp