Qubet: Menu Class Reference
Menu Class Reference
Menu class used to show and manage the game menu.
#include <menu.h>
Signals
void playStory (GLint skinId)
Signal emitted to show the gameView in story mode.
void playArcade (GLint skinId, GLint levelId)
Signal emitted to show the gameView in arcade mode.
void showLevelEditor (GLint levelId)
Signal emitted to show the levelEditor.
void setMouseMovementTracking (int mode)
This signal is emitted to set the Qubet's Mouse Move Tracking sensibility. The modes are: 0 - no signal emitted. 1 - the signal mouseMoved is emitted only when the mouse is moved and one of the mouse buttons are clicked. 2 - the signal mouseMoved is emitted always when the mouse is moved.
void enableAudio (bool enabled)
Signal emitted to enable or disable the audio.
void playAmbientMusic (QString filename)
Signal emitted to play the ambient music.
void stopAmbientMusic ()
Signal emitted to stop the current ambient music.
void playEffect (QString effectName)
Signal emitted to play an effect.
void setSkybox (QString skyboxName)
Signal emitted to set the Skybox.
Public Member Functions
Menu (QMap< GLint, Skin * > &_skinsList, QMap< GLint, Level * > &_levelsList, QMap< GLint, GLuint > &_iconsList, Alphabet *_alphabet, QObject *_parent, bool _audioEnabled=true, bool showIntro=true)
Create a Menu object used to show and manage the game menu.
~Menu ()
Disconnect and Destroy a Menu object.
GLvoid draw (GLboolean simplifyForPicking=false)
Method to draw the menu.
Private Slots
void itemClicked (QMouseEvent *event, QList< GLuint > listNames)
Slot invoked when the user clicks on a item.
void mouseReleased (QMouseEvent *event)
Slot invoked when the user releases the mouse button.
void mouseMoved (QMouseEvent *event, QList< GLuint > listNames)
Slot invoked when the user moves the mouse.
void wheelScrolled (QWheelEvent *event)
Slot invoked when the user scrolls the wheel of the mouse button.
void keyPressed (QKeyEvent *event)
Slot invoked when the user presses a key on the keyboard.
Private Member Functions
GLvoid previousSkin ()
Change the current skin and select the previous one.
GLvoid nextSkin ()
Change the current skin and select the next one.
GLvoid previousLevel ()
Select the previous level.
GLvoid nextLevel ()
Select the next level.
GLvoid buttonPlayStoryTriggered ()
This function is invoked when playStoryButton is triggered.
GLvoid buttonPlayArcadeTriggered ()
This function is invoked when playArcadeButton is triggered.
GLvoid buttonEditorTriggered ()
This function is invoked when editorButton is triggered.
GLvoid buttonBackTriggered ()
This function is invoked when backButton is triggered.
GLvoid buttonNextTriggered ()
This function is invoked when nextButton is triggered.
GLvoid buttonPreviousSkinTriggered ()
This function is invoked when previousSkinButton is triggered.
GLvoid buttonNextSkinTriggered ()
This function is invoked when nextSkinButton is triggered.
Private Attributes
QObject * parent
GLint currentSkin
GLint currentLevel
QMap< GLint, Skin * > skinsList
QMap< GLint, Level * > levelsList
QMap< GLint, GLuint > iconsList
Alphabet * alphabet
GLint itemSelected
GLboolean isMoving
Vector3f * cameraOffset
ActionList * currentActions
GLint gameType
GLfloat angleRotCube
GLfloat spinCube
GLfloat angleRotVolumeCube
GLboolean audioEnabled
Skin * volumeSkin
GLint currentView
GLint currentSection
GLint waitCounter
CubeStringList * mainMenuButtons
CubeString * skinName
CubeStringList * levelName
CubeString * backButton
CubeString * playButton
CubeString * levelsButton
CubeString * editButton
CubeStringList * cubeStudiosLabel
CubeStringList * team34Label
CubeString * qubetLabel
Detailed Description
Menu class used to show and manage the game menu.
Version:
1.0
Author:
#34
Constructor & Destructor Documentation
Menu::Menu (QMap< GLint, Skin * > & _skinsList, QMap< GLint, Level * > & _levelsList, QMap< GLint, GLuint > & _iconsList, Alphabet * _alphabet, QObject * _parent, bool _audioEnabled = true, bool showIntro = true) [explicit]
Create a Menu object used to show and manage the game menu.
Postcondition:
You have to connect parent's signals to this object's slots. For Qubet check the connectInputEvents function.
Parameters:
_skinsList is the reference to Qubet's skinsList.
_levelsList is the reference to Qubet's levelsList.
_iconsList is the reference to Qubet's iconsList.
_alphabet is the reference to Qubet's alphabet.
_parent is a callback variable to the parent of the parent.
_audioEnabled is a variable to states if the audio is enabled or not.
showIntro states if you want to show the intro. [default = true]
References alphabet, angleRotVolumeCube, audioEnabled, backButton, cameraOffset, cubeStudiosLabel, currentActions, currentSection, currentSkin, currentView, editButton, iconsList, levelName, levelsButton, mainMenuButtons, parent, playAmbientMusic(), playButton, qubetLabel, CubeString::setCurrentAngle(), CubeStringList::setCurrentAngle(), setMouseMovementTracking(), setSkybox(), skinName, skinsList, CubeStringList::startStringListRotation(), team34Label, volumeSkin, Vector3f::x, and Vector3f::y.
Member Function Documentation
GLvoid Menu::draw (GLboolean simplifyForPicking = false)
Method to draw the menu.
Parameters:
simplifyForPicking [default = false] is used to draw a simplified scene used for the picking function.
References angleRotCube, angleRotVolumeCube, backButton, cameraOffset, cubeStudiosLabel, currentActions, currentLevel, currentSection, currentSkin, currentView, CubeString::draw(), CubeStringList::draw(), editButton, gameType, ActionList::getAllActions(), isMoving, levelName, levelsButton, mainMenuButtons, nextSkin(), parent, playArcade(), playButton, playStory(), previousSkin(), qubetLabel, ActionList::removeSecondaryAction(), setMouseMovementTracking(), ActionList::setPrimaryAction(), showLevelEditor(), skinName, skinsList, spinCube, CubeStringList::startStringListRotation(), CubeString::startStringRotation(), team34Label, volumeSkin, waitCounter, Vector3f::x, Vector3f::y, and Vector3f::z.
Referenced by Qubet::drawScene().
void Menu::enableAudio (bool enabled) [signal]
Signal emitted to enable or disable the audio.
Parameters:
enabled is the variable that states if the audio is to enable or not.
Referenced by itemClicked().
void Menu::itemClicked (QMouseEvent * event, QList< GLuint > listNames) [private, slot]
Slot invoked when the user clicks on a item.
Parameters:
event is the QMouseEvent.
listNames is the QList<GLuint> of item's names.
References angleRotVolumeCube, ActionList::appendSecondaryAction(), audioEnabled, buttonBackTriggered(), buttonEditorTriggered(), buttonNextSkinTriggered(), buttonNextTriggered(), buttonPlayArcadeTriggered(), buttonPlayStoryTriggered(), buttonPreviousSkinTriggered(), currentActions, enableAudio(), isMoving, nextLevel(), and previousLevel().
void Menu::keyPressed (QKeyEvent * event) [private, slot]
Slot invoked when the user presses a key on the keyboard.
Parameters:
event is the QKeyEvent*.
References buttonBackTriggered(), buttonEditorTriggered(), buttonNextSkinTriggered(), buttonNextTriggered(), buttonPlayArcadeTriggered(), buttonPlayStoryTriggered(), buttonPreviousSkinTriggered(), currentView, isMoving, nextLevel(), and previousLevel().
void Menu::mouseMoved (QMouseEvent * event, QList< GLuint > listNames) [private, slot]
Slot invoked when the user moves the mouse.
Parameters:
event is the QMouseEvent*.
listNames is the QList<GLuint> of item's names.
References isMoving, CubeString::isRotating(), CubeStringList::isRotating(), levelName, mainMenuButtons, skinName, CubeString::startLetterRotation(), and CubeStringList::startLetterRotation().
void Menu::mouseReleased (QMouseEvent * event) [private, slot]
Slot invoked when the user releases the mouse button.
Parameters:
event is the QMouseEvent*.
void Menu::playAmbientMusic (QString filename) [signal]
Signal emitted to play the ambient music.
Parameters:
filename is the filename to play.
Referenced by Menu().
void Menu::playArcade (GLint skinId, GLint levelId) [signal]
Signal emitted to show the gameView in arcade mode.
Parameters:
skinId
levelId
Referenced by draw().
void Menu::playEffect (QString effectName) [signal]
Signal emitted to play an effect.
Parameters:
effectName is the name of the effect to play.
Referenced by buttonBackTriggered(), buttonEditorTriggered(), buttonNextTriggered(), buttonPlayArcadeTriggered(), buttonPlayStoryTriggered(), nextLevel(), nextSkin(), previousLevel(), and previousSkin().
void Menu::playStory (GLint skinId) [signal]
Signal emitted to show the gameView in story mode.
Parameters:
skinId
Referenced by draw().
void Menu::setMouseMovementTracking (int mode) [signal]
This signal is emitted to set the Qubet's Mouse Move Tracking sensibility. The modes are: 0 - no signal emitted. 1 - the signal mouseMoved is emitted only when the mouse is moved and one of the mouse buttons are clicked. 2 - the signal mouseMoved is emitted always when the mouse is moved.
Parameters:
mode It is the selected mode.
Referenced by draw(), and Menu().
void Menu::setSkybox (QString skyboxName) [signal]
Signal emitted to set the Skybox.
Parameters:
skyboxName is the name of the Skybox to apply.
Referenced by Menu().
void Menu::wheelScrolled (QWheelEvent * event) [private, slot]
Slot invoked when the user scrolls the wheel of the mouse button.
Parameters:
event is the QWheelEvent*.
Member Data Documentation
Alphabet* Menu::alphabet [private]
It is the alphabet provided by Qubet.
Referenced by buttonEditorTriggered(), Menu(), nextLevel(), nextSkin(), previousLevel(), and previousSkin().
GLfloat Menu::angleRotCube [private]
It is the current rotation angle of the cube.
Referenced by draw().
GLfloat Menu::angleRotVolumeCube [private]
It is the current rotation angle of the volume icon.
Referenced by draw(), itemClicked(), and Menu().
GLboolean Menu::audioEnabled [private]
It is the state of the audio.
Referenced by itemClicked(), and Menu().
CubeString* Menu::backButton [private]
It is the backButton CubeString.
Referenced by draw(), Menu(), and ~Menu().
Vector3f* Menu::cameraOffset [private]
It is the camera offset for the menu.
Referenced by draw(), and Menu().
CubeStringList* Menu::cubeStudiosLabel [private]
It is the Cube studios distribution CubeStringList.
Referenced by draw(), Menu(), and ~Menu().
ActionList* Menu::currentActions [private]
It is the list of the current menu steps.
Referenced by buttonBackTriggered(), buttonEditorTriggered(), buttonNextSkinTriggered(), buttonNextTriggered(), buttonPlayArcadeTriggered(), buttonPlayStoryTriggered(), buttonPreviousSkinTriggered(), draw(), itemClicked(), and Menu().
GLint Menu::currentLevel [private]
It is the id of the current choosen level.
Referenced by buttonEditorTriggered(), buttonNextTriggered(), draw(), nextLevel(), and previousLevel().
GLint Menu::currentSection [private]
It is used to states the menu to draw the introduction or the menu.
Referenced by draw(), and Menu().
GLint Menu::currentSkin [private]
It is the id of the current choosen skin.
Referenced by draw(), Menu(), nextSkin(), and previousSkin().
GLint Menu::currentView [private]
It is the value of the current view
Referenced by buttonBackTriggered(), buttonEditorTriggered(), buttonNextSkinTriggered(), buttonNextTriggered(), buttonPlayArcadeTriggered(), buttonPlayStoryTriggered(), buttonPreviousSkinTriggered(), draw(), keyPressed(), and Menu().
CubeString* Menu::editButton [private]
It is the editButton CubeString.
Referenced by draw(), Menu(), and ~Menu().
GLint Menu::gameType [private]
It is the selected gameType.
Referenced by buttonBackTriggered(), buttonEditorTriggered(), buttonNextTriggered(), buttonPlayArcadeTriggered(), buttonPlayStoryTriggered(), draw(), nextLevel(), and previousLevel().
QMap<GLint,GLuint> Menu::iconsList [private]
It is the iconsList provided by Qubet object.
Referenced by Menu().
GLboolean Menu::isMoving [private]
It is the variable that states if the menu is moving or not.
Referenced by buttonBackTriggered(), buttonEditorTriggered(), buttonNextSkinTriggered(), buttonNextTriggered(), buttonPlayArcadeTriggered(), buttonPlayStoryTriggered(), buttonPreviousSkinTriggered(), draw(), itemClicked(), keyPressed(), and mouseMoved().
GLint Menu::itemSelected [private]
It is the id of the current menu action selected.
CubeStringList* Menu::levelName [private]
It is the levelName CubeString.
Referenced by buttonEditorTriggered(), draw(), Menu(), mouseMoved(), nextLevel(), previousLevel(), and ~Menu().
CubeString* Menu::levelsButton [private]
It is the levelsButton CubeString.
Referenced by draw(), Menu(), and ~Menu().
QMap<GLint,Level*> Menu::levelsList [private]
It is the levelsList provided by Qubet object.
Referenced by nextLevel(), and previousLevel().
CubeStringList* Menu::mainMenuButtons [private]
It is the main menu buttons stringList.
Referenced by draw(), Menu(), mouseMoved(), and ~Menu().
QObject* Menu::parent [private]
It is a callback variable to the parent of the widget.
Referenced by draw(), Menu(), and ~Menu().
CubeString* Menu::playButton [private]
It is the playButton CubeString.
Referenced by draw(), Menu(), and ~Menu().
CubeString* Menu::qubetLabel [private]
It is the Qubet CubeString.
Referenced by draw(), Menu(), and ~Menu().
CubeString* Menu::skinName [private]
It is the skinName CubeString.
Referenced by draw(), Menu(), mouseMoved(), nextSkin(), previousSkin(), and ~Menu().
QMap<GLint,Skin*> Menu::skinsList [private]
It is the skinsList provided by Qubet object.
Referenced by draw(), Menu(), nextSkin(), and previousSkin().
GLfloat Menu::spinCube [private]
It is the spin step of the skin selection cube.
Referenced by draw().
CubeStringList* Menu::team34Label [private]
It is the team 34 CubeStringList.
Referenced by draw(), Menu(), and ~Menu().
Skin* Menu::volumeSkin [private]
It is the skin of the volume button
Referenced by draw(), Menu(), and ~Menu().
GLint Menu::waitCounter [private]
It is an incremental variable to wait from intro screens.
Referenced by draw().
The documentation for this class was generated from the following files:
menu.h
menu.cpp