Qubet: ActionList Class Reference
ActionList Class Reference
This class is used to keep track of actions to do. For example it can keep track of current view scrolling movement, or cube rotations.
#include <actionlist.h>
Public Member Functions
ActionList ()
Creates a new ActionList with no secondaryActions and 0 as primaryAction.
ActionList (int _primaryAction)
Creates a new ActionList with no secondaryActions and primaryAction given as parameter.
ActionList (ActionList *other)
Creates a new ActionList as a copy of another ActionList.
~ActionList ()
Safely removes an ActionList.
void setPrimaryAction (int _primaryAction)
Set the given parameter as the new primaryAction, overriding the old one.
int getPrimaryAction ()
Returns the current primaryAction.
void appendSecondaryAction (int _secondaryAction)
Appends a secondary action to secondaryActions list.
void removeSecondaryAction (int _secondaryAction)
Removes a secondary action to secondaryActions list.
QList< int > getSecondaryActions ()
Returns the secondaryActions list.
QList< int > getAllActions ()
Returns a list of primary and secondary actions.
Private Attributes
int primaryAction
QList< int > secondaryActions
Detailed Description
This class is used to keep track of actions to do. For example it can keep track of current view scrolling movement, or cube rotations.
There are two type of actions: Primary and Secondary actions.
Primary action: You can keep track of only one primary action at a moment, it is used for example for the scrolling of menu views, only one scrolling at a time. When you set a primary action the new one automatically overrides the old one.
Secondary actions: You can keep track of infinite secondary actions at a moment, these actions are concurrent toghether and concurrent to the primary action. They are used for concurrent allowed actions like a Seconday Cube Rotation. You have to manually remove a secondary action when you want to stop it, since appending another secondary action will not override the old one (it is a list).
You can have an example of this in Qubet's menu.
Version:
1.0
Author:
#34
Constructor & Destructor Documentation
ActionList::ActionList (int _primaryAction) [explicit]
Creates a new ActionList with no secondaryActions and primaryAction given as parameter.
Parameters:
_primaryAction is the primary action to set to the actionList.
ActionList::ActionList (ActionList * other) [explicit]
Creates a new ActionList as a copy of another ActionList.
Parameters:
other is the actionList to copy.
References getPrimaryAction(), getSecondaryActions(), primaryAction, and secondaryActions.
Member Function Documentation
void ActionList::appendSecondaryAction (int _secondaryAction)
Appends a secondary action to secondaryActions list.
Parameters:
_secondaryAction is the secondary action to append.
References secondaryActions.
Referenced by Menu::itemClicked(), LevelEditor::itemClicked(), and Game::itemClicked().
QList< int > ActionList::getAllActions ()
Returns a list of primary and secondary actions.
It is the current secondaryActions list, prepending the primaryAction.
Returns:
a list of primary and secondary actions.
References primaryAction, and secondaryActions.
Referenced by Menu::draw(), LevelEditor::draw(), and Game::draw().
int ActionList::getPrimaryAction ()
Returns the current primaryAction.
Returns:
The current primaryAction.
References primaryAction.
Referenced by ActionList(), Game::draw(), and Game::keyPressed().
QList< int > ActionList::getSecondaryActions ()
Returns the secondaryActions list.
Returns:
the secondaryActions list.
References secondaryActions.
Referenced by ActionList().
void ActionList::removeSecondaryAction (int _secondaryAction)
Removes a secondary action to secondaryActions list.
Parameters:
_secondaryAction is the secondary action to remove.
References secondaryActions.
Referenced by Menu::draw(), LevelEditor::draw(), and Game::draw().
void ActionList::setPrimaryAction (int _primaryAction)
Set the given parameter as the new primaryAction, overriding the old one.
Parameters:
_primaryAction is the primaryAction to set.
References primaryAction.
Referenced by Menu::buttonBackTriggered(), LevelEditor::buttonBackTriggered(), Menu::buttonEditorTriggered(), Menu::buttonNextSkinTriggered(), Menu::buttonNextTriggered(), LevelEditor::buttonNextTriggered(), Menu::buttonPlayArcadeTriggered(), Menu::buttonPlayStoryTriggered(), Menu::buttonPreviousSkinTriggered(), Game::countdown(), Game::createResultStrings(), Menu::draw(), LevelEditor::draw(), Game::draw(), Game::nextLevel(), LevelEditor::quitEditor(), and Game::quitGame().
Member Data Documentation
int ActionList::primaryAction [private]
It is the current primary action of the ActionList.
Referenced by ActionList(), getAllActions(), getPrimaryAction(), and setPrimaryAction().
QList<int> ActionList::secondaryActions [private]
It is a list of the current secondary actions of the ActionList
Referenced by ActionList(), appendSecondaryAction(), getAllActions(), getSecondaryActions(), removeSecondaryAction(), and ~ActionList().
The documentation for this class was generated from the following files:
actionlist.h
actionlist.cpp