Qubet: CubeStringList Class Reference
CubeStringList Class Reference
This class is used to draw a vertical list of CubeString. Look at CubeString to have a better specification of the class.
#include <cubestringlist.h>
Public Member Functions
CubeStringList (QList< QPair< QString, GLuint > > _labels, GLfloat _cubeDimension, Alphabet *_alphabet)
Creates a CubeStringList from a QList of QPair, the first item of each pair is the string to draw, the second the OpenGL name you want to give the string. Using this constructor you can define the dimension of the cubes.
CubeStringList (QList< QPair< QString, GLuint > > _labels, GLfloat _maxWidth, GLfloat _maxHeight, Alphabet *_alphabet, GLfloat _maxCubeDimension=0.0f)
Creates a CubeStringList from a QList of QPair, the first item of each pair is the string to draw, the second the OpenGL name you want to give the string. Using this constructor you can define a maximum space the CubeStringList can grow, the class then will manage the list to fit this space.
CubeStringList (QString _labels, GLfloat _cubeDimension, Alphabet *_alphabet, GLuint _name=0)
Creates a CubeStringList from QString, it will be splitted on the character space to tokenize the string and create the list of words. You can also set the OpenGL name of the CubeStringList (the same for all the lines). Using this constructor you can define a maximum space the CubeStringList can grow, the class then will manage the list to fit this space.
CubeStringList (QString _labels, GLfloat _maxWidth, GLfloat _maxHeight, Alphabet *_alphabet, GLfloat _maxCubeDimension=0.0f, GLuint _name=0)
Creates a CubeStringList from QString, it will be splitted on the character space to tokenize the string and create the list of words. You can also set the OpenGL name of the CubeStringList (the same for all the lines). Using this constructor you can define a maximum space the CubeStringList can grow, the class then will manage the list to fit this space.
~CubeStringList ()
Safely destroy a CubeStringList.
GLvoid draw (GLboolean simplifyForPicking=false)
Draws the CubeStringList at the current position.
GLint getLabelCount ()
Returns the number of labels in the CubeStringList.
QString getLabel (GLuint _stringName)
Returns the label which name is _stringName.
GLvoid startLetterRotation (GLuint _stringName, GLuint _letterName, GLint _angleStep, GLint _turns)
Start the rotation of a single letter in a single CubeString contained in the CubeStrigList.
GLvoid startStringRotation (GLuint _stringName, GLint _angleStep, GLint _turns)
Start the rotation of a whole CubeString contained in the CubeStringList.
GLvoid startStringListRotation (GLint _angleStep, GLint _turns)
Start the rotation of the whole CubeStringList (woo-woo-wao).
GLboolean isRotating (GLuint _stringName, GLuint _letterName)
Check if a letter of the CubeString is already rotating.
GLfloat setCurrentAngle (GLfloat _firstLetterAngle, GLfloat _nextLetterDelta=0.0f)
Set the current angle for the letters in the CubeString.
Private Member Functions
GLvoid computeHeights (GLfloat _cubeDimension)
It compute the heights (firstStringHeight and stringsHeightDelta) basing on constructor parameters.
CubeString * getCubeStringFromName (GLuint _name)
Return a pointer to the CubeString having the parameter OpenGL name.
CubeString * getCubeStringFromLabel (QString _label)
Return a pointer to the CubeString having the parameter label.
QList< QPair< QString, GLuint > > splitLabels (QString _labels)
Split the QString in a QList of QPair.
GLvoid init (QList< QPair< QString, GLuint > > _labels, GLfloat _cubeDimension, Alphabet *_alphabet)
Common part to the constructors that uses the cubeDimension.
GLvoid init (QList< QPair< QString, GLuint > > _labels, GLfloat _maxWidth, GLfloat _maxHeight, Alphabet *_alphabet, GLfloat _maxCubeDimension=0.0f)
Common part to the constructors that uses the maxWidth and maxHeight.
Private Attributes
QList< CubeString * > cubeStrings
GLuint name
GLfloat interline
GLfloat firstStringHeight
GLfloat stringsHeightDelta
Detailed Description
This class is used to draw a vertical list of CubeString. Look at CubeString to have a better specification of the class.
Version:
1.0
Author:
#34
Constructor & Destructor Documentation
CubeStringList::CubeStringList (QList< QPair< QString, GLuint > > _labels, GLfloat _cubeDimension, Alphabet * _alphabet) [explicit]
Creates a CubeStringList from a QList of QPair, the first item of each pair is the string to draw, the second the OpenGL name you want to give the string. Using this constructor you can define the dimension of the cubes.
Parameters:
_labels is a QList of QPair, the first item of each pair is the string to draw, the second the OpenGL name you want to give the string.
_cubeDimension is the dimension of each cube of the single CubeString.
_alphabet is the Alphabet to use.
References init().
CubeStringList::CubeStringList (QList< QPair< QString, GLuint > > _labels, GLfloat _maxWidth, GLfloat _maxHeight, Alphabet * _alphabet, GLfloat _maxCubeDimension = 0.0f) [explicit]
Creates a CubeStringList from a QList of QPair, the first item of each pair is the string to draw, the second the OpenGL name you want to give the string. Using this constructor you can define a maximum space the CubeStringList can grow, the class then will manage the list to fit this space.
Parameters:
_labels is a QList of QPair, the first item of each pair is the string to draw, the second the OpenGL name you want to give the string.
_maxWidth is the maximum width the CubeStringList can grow.
_maxHeight is the maximum height the CubeStringList can grow.
_alphabet is the Alphabet to use.
_maxCubeDimension is the maximum cubeDimension. If set to a number <= 0.0f it will not be computated. [default = 0.0f]
References init().
CubeStringList::CubeStringList (QString _labels, GLfloat _cubeDimension, Alphabet * _alphabet, GLuint _name = 0) [explicit]
Creates a CubeStringList from QString, it will be splitted on the character space to tokenize the string and create the list of words. You can also set the OpenGL name of the CubeStringList (the same for all the lines). Using this constructor you can define a maximum space the CubeStringList can grow, the class then will manage the list to fit this space.
Parameters:
_labels is the QString that will be splitted on the character space to create the list of words.
_cubeDimension is the dimension of each cube of the single CubeString.
_alphabet is the Alphabet to use.
_name is the OpenGL name of the CubeStringList (the same for all the lines). [default = 0]
References init(), and splitLabels().
CubeStringList::CubeStringList (QString _labels, GLfloat _maxWidth, GLfloat _maxHeight, Alphabet * _alphabet, GLfloat _maxCubeDimension = 0.0f, GLuint _name = 0) [explicit]
Creates a CubeStringList from QString, it will be splitted on the character space to tokenize the string and create the list of words. You can also set the OpenGL name of the CubeStringList (the same for all the lines). Using this constructor you can define a maximum space the CubeStringList can grow, the class then will manage the list to fit this space.
Parameters:
_labels is the QString that will be splitted on the character space to create the list of words.
_maxWidth is the maximum width the CubeStringList can grow.
_maxHeight is the maximum height the CubeStringList can grow.
_alphabet is the Alphabet to use.
_maxCubeDimension is the maximum cubeDimension. If set to a number <= 0.0f it will not be computated. [default = 0.0f]
_name is the OpenGL name of the CubeStringList (the same for all the lines). [default = 0]
References init(), and splitLabels().
Member Function Documentation
GLvoid CubeStringList::computeHeights (GLfloat _cubeDimension) [private]
It compute the heights (firstStringHeight and stringsHeightDelta) basing on constructor parameters.
Parameters:
_cubeDimension is the dimension of the cubes.
References cubeStrings, firstStringHeight, interline, and stringsHeightDelta.
Referenced by init().
GLvoid CubeStringList::draw (GLboolean simplifyForPicking = false)
Draws the CubeStringList at the current position.
Parameters:
simplifyForPicking is the is used to draw a simplified scene used for the picking function and does not compute the change to angles. [default = false]
References cubeStrings, CubeString::draw(), firstStringHeight, name, and stringsHeightDelta.
Referenced by Menu::draw(), and LevelEditor::draw().
CubeString * CubeStringList::getCubeStringFromLabel (QString _label) [private]
Return a pointer to the CubeString having the parameter label.
Parameters:
_label is the label you want the CubeString.
Returns:
a pointer to the CubeString having the parameter OpenGL label.
References cubeStrings, and CubeString::getLabel().
CubeString * CubeStringList::getCubeStringFromName (GLuint _name) [private]
Return a pointer to the CubeString having the parameter OpenGL name.
Parameters:
_name is the OpenGL name you want the CubeString.
Returns:
a pointer to the CubeString having the parameter OpenGL name.
References cubeStrings, and CubeString::getName().
Referenced by getLabel(), isRotating(), startLetterRotation(), and startStringRotation().
QString CubeStringList::getLabel (GLuint _stringName)
Returns the label which name is _stringName.
Parameters:
_stringName is the name of the string you want the label.
Returns:
the label which name is _stringName.
References getCubeStringFromName(), and CubeString::getLabel().
Referenced by LevelEditor::draw(), and LevelEditor::letterTyped().
GLint CubeStringList::getLabelCount ()
Returns the number of labels in the CubeStringList.
Returns:
the number of labels in the CubeStringList.
References cubeStrings.
Referenced by LevelEditor::letterTyped().
GLvoid CubeStringList::init (QList< QPair< QString, GLuint > > _labels, GLfloat _cubeDimension, Alphabet * _alphabet) [private]
Common part to the constructors that uses the cubeDimension.
Parameters:
_labels is the QString that will be splitted on the character space to create the list of words.
_cubeDimension is the dimension of each cube of the single CubeString.
_alphabet is the Alphabet to use.
References computeHeights(), cubeStrings, and interline.
Referenced by CubeStringList(), and init().
GLvoid CubeStringList::init (QList< QPair< QString, GLuint > > _labels, GLfloat _maxWidth, GLfloat _maxHeight, Alphabet * _alphabet, GLfloat _maxCubeDimension = 0.0f) [private]
Common part to the constructors that uses the maxWidth and maxHeight.
Parameters:
_labels is the QString that will be splitted on the character space to create the list of words.
_maxWidth is the maximum width the CubeStringList can grow.
_maxHeight is the maximum height the CubeStringList can grow.
_alphabet is the Alphabet to use.
_maxCubeDimension is the maximum cubeDimension. If set to a number <= 0.0f it will not be computated. [default = 0.0f]
References init().
GLboolean CubeStringList::isRotating (GLuint _stringName, GLuint _letterName)
Check if a letter of the CubeString is already rotating.
Parameters:
_stringName is the name of the string (it is the second name (after the entire list name) in the nameList of the picking function. You don't have to know which is, let the picking function and the CubeStringList code work for you.
_letterName is the name of the letter (it is the third name (after the entire list and the string names) in the nameList of the picking function. You don't have to know which is, let the picking function and the CubeStringList code work for you.
References getCubeStringFromName(), and CubeString::isRotating().
Referenced by LevelEditor::letterTyped(), and Menu::mouseMoved().
GLfloat CubeStringList::setCurrentAngle (GLfloat _firstLetterAngle, GLfloat _nextLetterDelta = 0.0f)
Set the current angle for the letters in the CubeString.
Parameters:
_firstLetterAngle is the angle of the current letter of the CubeStringList.
_nextLetterDelta is the delta you want to apply from the previous and the next letter's angle. [default = 0]
Returns:
the angle the next letter after this CubeString should have.
References cubeStrings, and CubeString::setCurrentAngle().
Referenced by Menu::Menu().
QList< QPair< QString, GLuint > > CubeStringList::splitLabels (QString _labels) [private]
Split the QString in a QList of QPair.
Parameters:
_labels is the QString to split.
Returns:
the splitted QList of QPair.
Referenced by CubeStringList().
GLvoid CubeStringList::startLetterRotation (GLuint _stringName, GLuint _letterName, GLint _angleStep, GLint _turns)
Start the rotation of a single letter in a single CubeString contained in the CubeStrigList.
If you use this function when a letter is already rotating, the _turns will be summed to the current rotation but the new _angleStep will be used only if: (current angleStep) % _angleStep == 0 This is the only sure way to keep the validity.
Warning:
In order to prevent infinite rotations, only valid rotations will be accepted, a rotation is valid if: (_turns * 90) % _angleStep == 0
Parameters:
_stringName is the string that contains the letter you want to start the rotation.
_letterName is the name of the Letter (it is the second name (after the entire string name) in the nameList of the picking function. You don't have to know which is, let the picking function and the CubeString code work for you.
_angleStep is the angle that will be summed to letter on each frame.
_turns is an integer that states how many 90 degrees turns you want the letter to do.
References getCubeStringFromName(), and CubeString::startLetterRotation().
Referenced by LevelEditor::letterTyped(), and Menu::mouseMoved().
GLvoid CubeStringList::startStringListRotation (GLint _angleStep, GLint _turns)
Start the rotation of the whole CubeStringList (woo-woo-wao).
Parameters:
_angleStep is the angle that will be summed to every letter on each frame.
_turns is an integer that states how many 90 degrees turns you want each letter to do.
References cubeStrings, and CubeString::startStringRotation().
Referenced by Menu::draw(), and Menu::Menu().
GLvoid CubeStringList::startStringRotation (GLuint _stringName, GLint _angleStep, GLint _turns)
Start the rotation of a whole CubeString contained in the CubeStringList.
If you use this function when a CubeString is already rotating, the _turns will be summed to the current rotation but the new _angleStep will be used only if: (current angleStep) % _angleStep == 0 This is the only sure way to keep the validity.
Warning:
In order to prevent infinite rotations, only valid rotations will be accepted, a rotation is valid if: (_turns * 90) % _angleStep == 0
Parameters:
_stringName is the string you want to start the rotation.
_angleStep is the angle that will be summed to every letter on each frame.
_turns is an integer that states how many 90 degrees turns you want each letter to do.
References getCubeStringFromName(), and CubeString::startStringRotation().
Member Data Documentation
QList<CubeString*> CubeStringList::cubeStrings [private]
It is the list of CubeStrings.
Referenced by computeHeights(), draw(), getCubeStringFromLabel(), getCubeStringFromName(), getLabelCount(), init(), setCurrentAngle(), startStringListRotation(), and ~CubeStringList().
GLfloat CubeStringList::firstStringHeight [private]
It is the height of the first string of the list.
Referenced by computeHeights(), and draw().
GLfloat CubeStringList::interline [private]
It is the interline from one line to the following one.
Referenced by computeHeights(), and init().
GLuint CubeStringList::name [private]
It is the OpenGL name of the CubeStringList.
Referenced by draw().
GLfloat CubeStringList::stringsHeightDelta [private]
It is the delta from the centers of two strings in the list.
Referenced by computeHeights(), and draw().
The documentation for this class was generated from the following files:
cubestringlist.h
cubestringlist.cpp