Qubet: PositionController Class Reference
PositionController Class Reference
PositionController Class check if the cube has a collision with obstacles.
#include <positioncontroller.h>
Signals
void collision ()
Signal emitted when the cube has a collision with an obstacle.
Public Member Functions
PositionController (Cube *_cube, Level *_level, QObject *_parent=0)
Create a PositionController Objects.
~PositionController ()
Destroy a PositionController Object.
void startChecking ()
Start checking for collision.
void stopChecking ()
Stop checking for collisions.
Private Slots
void checkCollision ()
Check if the cube has a collision with an obstacle.
Private Member Functions
Vector3f * positionToCell (Vector3f *position)
Returns the cell coordinates from absolute position.
GLvoid createObstacleCells ()
Create the 3D Matrix of ObstacleCells.
void run ()
Reimplementation of the run() function of the QThread class.
bool isInteger (float f)
Check if a float is an integer.
Private Attributes
QObject * parent
Cube * cube
Level * level
GLint levelLength
GLint levelWidth
QTimer * checkPositionTimer
QVector< QVector< QVector
< bool > > > obstacleCells
Detailed Description
PositionController Class check if the cube has a collision with obstacles.
Version:
1.0
Author:
#34
Constructor & Destructor Documentation
PositionController::PositionController (Cube * _cube, Level * _level, QObject * _parent = 0) [explicit]
Create a PositionController Objects.
Parameters:
_cube is the cube Object pointer.
_level is the level Object pointer.
_parent is the parent Object pointer.
References checkCollision(), checkPositionTimer, collision(), createObstacleCells(), Level::getLength(), Level::getWidth(), level, levelLength, levelWidth, and parent.
Member Function Documentation
bool PositionController::isInteger (float f) [private]
Check if a float is an integer.
Parameters:
f is the float.
Returns:
true if is an integer.
Referenced by checkCollision().
Vector3f * PositionController::positionToCell (Vector3f * position) [private]
Returns the cell coordinates from absolute position.
Parameters:
position is the vector of absolute coordinates.
Returns:
the cell coordinates from absolute position.
References Vector3f::x, Vector3f::y, and Vector3f::z.
Referenced by checkCollision().
Member Data Documentation
QTimer* PositionController::checkPositionTimer [private]
QTimer controlling the checkCollision() calls.
Referenced by checkCollision(), PositionController(), startChecking(), stopChecking(), and ~PositionController().
Cube* PositionController::cube [private]
It is the pointer to the Cube Object.
Referenced by checkCollision().
Level* PositionController::level [private]
Is the pointer to the Level Object.
Referenced by createObstacleCells(), and PositionController().
GLint PositionController::levelLength [private]
It is the length of the Level.
Referenced by PositionController().
GLint PositionController::levelWidth [private]
It is the width of the Level.
Referenced by PositionController().
QVector<QVector<QVector<bool> > > PositionController::obstacleCells [private]
It is the 3d matrix rappresent obstacle cells
Referenced by checkCollision(), and createObstacleCells().
QObject* PositionController::parent [private]
It is the parent of the PositionController.
Referenced by PositionController(), and ~PositionController().
The documentation for this class was generated from the following files:
positioncontroller.h
positioncontroller.cpp