Qubet: Level Class Reference
Level Class Reference
This class rapresents a Level of Qubet, with its obstacle. It is able to draw itself simply using the draw function. It can also load the xml description file and parse it.
#include <level.h>
Public Member Functions
Level (QString _name, GLfloat _length, GLfloat _width, QObject *_parent=0, Skin *_asphaltSkin=NULL)
Creates a level from an id, a name, a length and a width. It is used to create a new Level from the LevelEditor.
Level (QString _filename, QObject *_parent=0, Skin *_asphaltSkin=NULL)
Creates a Level from a filename. It is used in the Loader.
~Level ()
Safely destroies a Level instance.
QString getFilename ()
Returns the filename of the Level.
void setFilename (QString _filename)
Set the Level filename.
QString getName ()
Returns the name of the Level.
void setName (QString _name)
Set the name of the Level.
bool getIsInStory ()
Returns the a variable that states if the Level is in the story.
void setIsInStory (bool _isInStory)
Set the a variable that states if the Level is in the story.
GLfloat getWidth ()
Returns the width of the Level.
GLfloat getLength ()
Returns the length of the Level.
GLfloat getGravity ()
Returns the gravity of the Level.
GLvoid setGravity (GLfloat _gravity)
Set the gravity of the Level.
QString getAmbientMusicFilename ()
Returns the ambient Music Filename.
QString getSkyboxName ()
Returns the Skybox Name.
void addObstacle (Obstacle *_obstacle)
Adds an obstacle to the Level.
void deleteObstacle (GLint _id)
Deletes an obstacle.
void moveObstacle (GLint _id, Vector3f *newCell)
Moves an obstacle to a new position.
QMap< GLint, Obstacle * > getObstaclesList ()
Returns the Level's Obstacles List.
bool load ()
Loads the Level from xml form using the filename as input.
bool save (bool *newlyCreated=0)
Saves the Level in a xml form using the filename as output.
GLvoid draw (GLboolean simplifyForPicking)
Draws the Level and its obstacles.
GLint getObstacleListCount ()
Returns the number of obstacles in the level.
GLvoid clearObstaclesList ()
Returns the number of obstacles in the level.
GLvoid clearTempObstaclesList ()
Clears the not saves obstacles.
Private Attributes
QObject * parent
QString filename
QString name
bool isInStory
QMap< GLint, Obstacle * > obstaclesList
QMap< GLint, Obstacle * > tempObstaclesList
GLint length
GLint width
GLfloat gravity
QString ambientMusicFilename
QString skyboxName
GLint currentObstacleId
bool isLoaded
Skin * asphaltSkin
Detailed Description
This class rapresents a Level of Qubet, with its obstacle. It is able to draw itself simply using the draw function. It can also load the xml description file and parse it.
Version:
1.0
Author:
#34
Constructor & Destructor Documentation
Level::Level (QString _name, GLfloat _length, GLfloat _width, QObject * _parent = 0, Skin * _asphaltSkin = NULL) [explicit]
Creates a level from an id, a name, a length and a width. It is used to create a new Level from the LevelEditor.
Parameters:
_name is the name of the Level.
_length is the length of the Level.
_width is the width of the Level.
_parent is the parent of the Level.
_asphaltSkin is the asphalt Skin for the Level.
References filename, and name.
Level::Level (QString _filename, QObject * _parent = 0, Skin * _asphaltSkin = NULL) [explicit]
Creates a Level from a filename. It is used in the Loader.
Parameters:
_filename is the filename to load.
_parent is the parent of the Level.
_asphaltSkin is the asphalt Skin for the Level.
References name.
Member Function Documentation
void Level::addObstacle (Obstacle * _obstacle)
Adds an obstacle to the Level.
Parameters:
_obstacle is the obstacle to add.
References currentObstacleId, Obstacle::setId(), and tempObstaclesList.
Referenced by LevelEditor::mouseReleased().
void Level::deleteObstacle (GLint _id)
Deletes an obstacle.
Parameters:
_id is the obstacle id.
References obstaclesList, and tempObstaclesList.
Referenced by LevelEditor::itemClicked().
GLvoid Level::draw (GLboolean simplifyForPicking)
Draws the Level and its obstacles.
Parameters:
simplifyForPicking is used to state if you want to draw it simplified.
References asphaltSkin, length, obstaclesList, tempObstaclesList, and width.
Referenced by LevelEditor::draw(), and Game::draw().
QString Level::getAmbientMusicFilename ()
Returns the ambient Music Filename.
Returns:
the ambientMusicFilename.
References ambientMusicFilename.
Referenced by Game::playLevel().
QString Level::getFilename ()
Returns the filename of the Level.
Returns:
the filename of the Level.
References filename.
GLfloat Level::getGravity ()
Returns the gravity of the Level.
Returns:
the gravity of the Level.
References gravity.
Referenced by Cube::Cube(), and LevelEditor::LevelEditor().
bool Level::getIsInStory ()
Returns the a variable that states if the Level is in the story.
Returns:
true if the Level is in the story, else false.
References isInStory.
Referenced by Game::nextLevel().
GLfloat Level::getLength ()
Returns the length of the Level.
Returns:
the length of the Level.
References length.
Referenced by PositionController::createObstacleCells(), Cube::Cube(), Game::draw(), LevelEditor::LevelEditor(), Game::playLevel(), and PositionController::PositionController().
QString Level::getName ()
Returns the name of the Level.
Returns:
the name of the Level.
References name.
Referenced by Game::playLevel().
GLint Level::getObstacleListCount ()
Returns the number of obstacles in the level.
Returns:
the number of obstacles in the level.
References obstaclesList.
QMap< GLint, Obstacle * > Level::getObstaclesList ()
Returns the Level's Obstacles List.
Returns:
the Level's Obstacles List.
References obstaclesList.
Referenced by PositionController::createObstacleCells().
QString Level::getSkyboxName ()
Returns the Skybox Name.
Returns:
the skyboxName.
References skyboxName.
Referenced by Game::playLevel().
GLfloat Level::getWidth ()
Returns the width of the Level.
Returns:
the width of the Level.
References width.
Referenced by PositionController::createObstacleCells(), Cube::Cube(), Game::draw(), LevelEditor::LevelEditor(), and PositionController::PositionController().
bool Level::load ()
Loads the Level from xml form using the filename as input.
Returns:
true if the load is successful, else false.
References ambientMusicFilename, currentObstacleId, filename, gravity, isLoaded, length, obstaclesList, skyboxName, and width.
Referenced by LevelEditor::LevelEditor(), and Game::playLevel().
void Level::moveObstacle (GLint _id, Vector3f * newCell)
Moves an obstacle to a new position.
Parameters:
_id is the id of the obstacle to move.
newCell is the new cell.
References obstaclesList.
bool Level::save (bool * newlyCreated = 0)
Saves the Level in a xml form using the filename as output.
Parameters:
newlyCreated is the return variable that is true is the level has been newly created, else false.
Returns:
true if save is successful, else false.
References filename, Obstacle::getCell(), Obstacle::getId(), Obstacle::getModelId(), gravity, isInStory, length, name, obstaclesList, tempObstaclesList, width, Vector3f::x, Vector3f::y, and Vector3f::z.
Referenced by LevelEditor::saveLevel().
void Level::setFilename (QString _filename)
Set the Level filename.
Parameters:
_filename is the filename to set.
References filename.
GLvoid Level::setGravity (GLfloat _gravity)
Set the gravity of the Level.
Parameters:
_gravity is the new gravity of the Level.
References gravity.
Referenced by LevelEditor::buttonNextTriggered().
void Level::setIsInStory (bool _isInStory)
Set the a variable that states if the Level is in the story.
Parameters:
_isInStory is the variable to set. (true if the Level is in the story, else false).
References isInStory.
Referenced by Qubet::loadLevels().
void Level::setName (QString _name)
Set the name of the Level.
Parameters:
_name is the name to set.
References name.
Referenced by Qubet::loadLevels().
Member Data Documentation
QString Level::ambientMusicFilename [private]
It is the Level ambient music filename.
Referenced by getAmbientMusicFilename(), and load().
Skin* Level::asphaltSkin [private]
It is the asphalt Skin.
Referenced by draw().
GLint Level::currentObstacleId [private]
It is the current Obstacle Id (used to generate new IDs).
Referenced by addObstacle(), and load().
QString Level::filename [private]
It is the Level xml description filename.
Referenced by getFilename(), Level(), load(), save(), and setFilename().
GLfloat Level::gravity [private]
It is the Level gravity.
Referenced by getGravity(), load(), save(), and setGravity().
bool Level::isInStory [private]
It is the variable that states if the Level is in the story.
Referenced by getIsInStory(), save(), and setIsInStory().
bool Level::isLoaded [private]
It is the variable that states if the level has already been fully loaded.
Referenced by load().
GLint Level::length [private]
It is the Level length.
Referenced by draw(), getLength(), load(), and save().
QString Level::name [private]
It is the Level name.
Referenced by getName(), Level(), save(), and setName().
QMap<GLint,Obstacle*> Level::obstaclesList [private]
It is the Level List of obstacles.
Referenced by clearObstaclesList(), deleteObstacle(), draw(), getObstacleListCount(), getObstaclesList(), load(), moveObstacle(), save(), and ~Level().
QObject* Level::parent [private]
It is the parent of Level.
QString Level::skyboxName [private]
It is the name of the skybox to use.
Referenced by getSkyboxName(), and load().
QMap<GLint,Obstacle*> Level::tempObstaclesList [private]
It is the Level List of obstacles.
Referenced by addObstacle(), clearTempObstaclesList(), deleteObstacle(), draw(), and save().
GLint Level::width [private]
It is the Level width.
Referenced by draw(), getWidth(), load(), and save().
The documentation for this class was generated from the following files:
level.h
level.cpp